services:
  api1:
    depends_on:
      - datadog
      - dbpostgres
    container_name: api1
    # image: service-a
    build: ./receiver
    ports:
      - "3000:8080"
    environment:
      DD_SERVICE: todos
      DD_TRACE_SERVICE_MAPPING: http-client:todos
      DD_ENV: local
      DD_VERSION: 1.0
      DD_TRACE_AGENT_URL: "http://datadog:8126"
  api2:
    depends_on:
      - datadog
      - api1
      - dbpostgres
    container_name: api2
    # image: service-a
    build: ./receiver-2
    ports:
      - "3001:8080"
    environment:
      DD_SERVICE: users
      DD_ENV: local
      DD_VERSION: 1.0
      DD_TRACE_AGENT_URL: "http://datadog:8126"
  dbpostgres:
    image: postgres
    volumes:
      - /Users/benjamen/Development/docker/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pgus
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
  datadog:
    image: datadog/agent:latest
    pid: host
    environment:
      - DD_API_KEY=<api key>
      - DD_SITE=us5.datadoghq.com
      - DD_LOG_LEVEL=CRITICAL
      - DD_ENV=local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
